#!/usr/bin/python
import os
from os.path import join
import argparse
import datetime

from pomodoro_config import *
import t

class External(object):
    pass

class Internal(object):
    pass

def build_parser():
    parser = argparse.ArgumentParser(description="Log a distraction.")
    parser.add_argument("text",
                        help="distraction description", metavar="TEXT")
    parser.add_argument("-e", "--external",
                        dest="type",
                        default=Internal, const=External, action="store_const",
                        help="mark the distraction as external")
    parser.add_argument("-i", "--internal",
                        dest="type",
                        default=Internal, const=Internal, action="store_const",
                        help="mark the distraction as internal (default)")
    parser.add_argument("-u", "--urgent",
                        default=False, action="store_true",
                        help="mark the distraction as urgent")
    parser.add_argument("-f", "--fatal",
                        default=False, action="store_true",
                        help="additionally stops the pomodoro")
    return parser

if __name__ == "__main__":
    args = build_parser().parse_args()

    today = datetime.date.today()
    filename = "{}-{}".format(SCHEDULE_FILE_PREFIX, str(today))

    todo = t.TaskDict(TASK_DIR, filename)
    inventory = t.TaskDict(TASK_DIR, INVENTORY_FILE)

    if not os.path.exists(join(SESSION_DIR, SESSION_FILE)):
        print("No pomodoro is in progress.")
        exit(1)

    current_task_id = open(join(TASK_DIR, CURRENT_TASK_FILE)).read()
    current_task = todo[current_task_id]

    if args.urgent:
        if args.fatal:
            os.remove(join(SESSION_DIR, SESSION_FILE))

        if args.type == Internal:
            todo.add_task(args.text)
            current_task['internal'] = str(int(current_task.get('internal', 0)) + 1)
            todo.tasks[current_task_id] = current_task
            inventory.tasks[current_task_id] = current_task
        elif args.type == External:
            todo.add_task(args.text)
            current_task['external'] = str(int(current_task.get('external', 0)) + 1)
            todo.tasks[current_task_id] = current_task
            inventory.tasks[current_task_id] = current_task
        inventory.write()
        todo.write()
    else:
        if args.type == Internal:
            inventory.add_task(args.text)
            current_task['internal'] = str(int(current_task.get('internal', 0)) + 1)
            todo.tasks[current_task_id] = current_task
            inventory.tasks[current_task_id] = current_task
        elif args.type == External:
            inventory.add_task(args.text)
            current_task['external'] = str(int(current_task.get('external', 0)) + 1)
            todo.tasks[current_task_id] = current_task
            inventory.tasks[current_task_id] = current_task
        inventory.write()
        todo.write()

