#!/usr/bin/python
import os
import sys
import argparse
import datetime

home = os.path.expanduser("~")
sys.path.append(home + os.sep + "bin")
import t

def build_parser():
    parser = argparse.ArgumentParser(description="Control the pomodoro.")
    parser.add_argument("task",
                        nargs="?",
                        help="task to start the pomodoro for", metavar="TASK")
    parser.add_argument("--done",
                        default=False, action="store_true",
                        help="mark the current pomodoro as completed")
    parser.add_argument("--resume",
                        default=False, action="store_true",
                        help="start another pomodoro with the previous task")
    return parser

if __name__ == "__main__":
    TASK_DIR = os.path.expanduser("~/docs/tasks/")
    args = build_parser().parse_args()

    today = datetime.date.today()
    filename = "todo-{}".format(str(today))

    todo = t.TaskDict(TASK_DIR, filename)

    if args.task:
        if len(todo.tasks) == 0:
            print("There are no tasks scheduled for today!")
            exit(0)

        task_id = todo[args.task]['id']
        with open(os.path.expanduser("~/docs/tasks/current"), 'w') as f:
            f.write(task_id)
        with open(os.path.expanduser("~/.pomodoro_session"), 'w'):
            pass
    elif args.done:
        try:
            with open(os.path.expanduser("~/docs/tasks/current"), 'r') as f:
                current_task_id = f.read()
                task = todo[current_task_id]
                task['marks'] = str(int(task.get('marks', 0)) + 1)
                todo.tasks[current_task_id] = task
                todo.write()
        except IOError as e:
            print("No task was previously started.")
    elif args.resume:
        try:
            with open(os.path.expanduser("~/docs/tasks/current"), 'r') as f:
                with open(os.path.expanduser("~/.pomodoro_session"), 'w'):
                    pass
        except IOError as e:
            print("A pomodoro is not currently in progress.")
    else:
        try:
            with open(os.path.expanduser("~/docs/tasks/current"), 'r') as f:
                current_task_id = f.read()
                task = todo[current_task_id]
                print(task['text'], task['id'], 'X' * int(task.get('marks', 0)))
        except IOError as e:
            print("A pomodoro is not currently in progress.")

