#!/usr/bin/python
import argparse
import datetime
import os

parser = argparse.ArgumentParser(description="Schedule task(s) for today from the activity inventory.")
parser.add_argument("tasks", metavar="TASK_ID", nargs="*", type=str, help="tasks to schedule for today")
args = parser.parse_args()

today = datetime.date.today()
filename = "todo-{}".format(str(today))
directory = "~/docs/tasks/"
path = os.path.expanduser(directory + filename)

if not os.path.exists(path):
    with open(path, "w"):
        pass

