#!/usr/bin/python

import os
import sys
import subprocess
import argparse

sys.path.append(os.getcwd() + os.sep + 't')
import t

def build_parser():
    parser = argparse.ArgumentParser(description="Manage activity inventory.")
    parser.add_argument("text",
                        nargs="?",
                        help="description of the task to add", metavar="TEXT")
    parser.add_argument("-r", "--remove",
                        nargs=1, dest="remove", action=StoreBoth,
                        help="remove TASK from the activity inventory", metavar="TASK")
    parser.add_argument("-e", "--edit",
                        nargs=2, dest="edit", action=StoreBoth,
                        help="edit TASK to contain TEXT (recalculates the hash)", metavar=("TASK", "TEXT"))
    parser.add_argument("-g", "--grep",
                        nargs=1, dest="grep", action="store",
                        default="",
                        help="print only tasks that contain WORD", metavar="WORD")
    parser.add_argument("-v", "--verbose",
                        dest="verbose", action="store_const",
                        default=False, const=True,
                        help="print more detailed output")
    parser.add_argument("-q", "--quiet",
                        dest="quiet", action="store_const",
                        default=False, const=False,
                        help="print less detailed output")
    return parser

if __name__ == "__main__":
    TASK_DIR = os.path.expanduser("~/docs/tasks/")
    INVENTORY_FILE = "tasks"
    args = build_parser().parse_args()

    inventory = t.TaskDict(TASK_DIR, INVENTORY_FILE)

    if args.remove:
        inventory.remove_task(args.remove[1])
        inventory.write()
    elif args.edit:
        option, task, text = args.edit
        # first delete the old task, so the hash gets recalculated
        inventory.remove_task(task)
        # add the new task
        inventory.add_task(text)
        inventory.write()
    elif args.text:
        inventory.add_task(args.text)
        inventory.write()
    else:
        inventory.print_list(verbose=args.verbose, quiet=args.quiet, grep=args.grep)

