#!/usr/bin/python

import os
import sys
import subprocess
import argparse

sys.path.append(os.getcwd() + os.sep + 't')
import t

def build_parser():
    parser = argparse.ArgumentParser(description="Manage activity inventory.")
    parser.add_argument("text",
                        nargs="?",
                        help="description of the task to add", metavar="TEXT")
    parser.add_argument("-r", "--remove",
                        nargs=1, dest="remove", action="store",
                        help="remove TASK from the activity inventory", metavar="TASK")
    parser.add_argument("-e", "--edit",
                        nargs=2, dest="edit", action="store",
                        help="edit TASK to contain TEXT (recalculates the hash)", metavar=("TASK", "TEXT"))
    parser.add_argument("-g", "--grep",
                        nargs=1, dest="grep", action="store",
                        default="",
                        help="print only tasks that contain WORD", metavar="WORD")
    parser.add_argument("-v", "--verbose",
                        dest="verbose", action="store_true",
                        default=False,
                        help="print more detailed output")
    parser.add_argument("-q", "--quiet",
                        dest="quiet", action="store_true",
                        default=False,
                        help="print less detailed output")
    parser.add_argument("--done",
                        dest="done", action="store_true",
                        default=False,
                        help="print completed tasks")
    return parser

if __name__ == "__main__":
    TASK_DIR = os.path.expanduser("~/docs/tasks/")
    INVENTORY_FILE = "tasks"
    args = build_parser().parse_args()

    inventory = t.TaskDict(TASK_DIR, INVENTORY_FILE)

    if args.remove:
        task_id = args.remove[0]
        inventory.remove_task(task_id)
        inventory.write()
    elif args.edit:
        task_id, text = args.edit
        # edit the task
        inventory.edit_task(task_id, text)
        # then remove and re-add it again so the hash gets recalculated
        task = inventory[task_id]
        inventory.remove_task(task_id)
        inventory.add_task(task['text'])
        inventory.write()
    elif args.text:
        inventory.add_task(args.text)
        inventory.write()
    else:
        kind = 'tasks' if not args.done else 'done'
        inventory.print_list(kind=kind, verbose=args.verbose, quiet=args.quiet, grep=args.grep)


